### ISSUE TITLE
关于使用您这套源码iOS兼容版本问题

### ISSUE THREAD

**Issue by samproppp** [yiyangest/react-native-baidumap#1]
我集成您这套源码进行iOS开发时，提示如下错误，您看能不能帮忙再解决一下，对此深表感谢！
**
object file (/Users/eyanlong/Library/Developer/Xcode/DerivedData/YiDaoJia-fhlfolkgkdlwsvflaywqfibrtuxv/Build/Products/Debug-iphoneos/libRCTBaiduMap.a(RCTConvert+BaiduMapKit.o)) was built for newer iOS version (9.2) than being linked (7.0)

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in BaiduMapAPI_Base(VDeviceAPI.o)
  "std::string::compare(std::string const&) const", referenced from:
      _baidu_framework::HandleBasemapMerge(_baidu_vi::CVString const&, _baidu_vi::CVString const&, _baidu_vi::CVString const&, char const_) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
  "std::basic_filebuf<char, std::char_traits<char> >::is_open() const", referenced from:
      _baidu_framework::HandleBasemapMerge(_baidu_vi::CVString const&, _baidu_vi::CVString const&, _baidu_vi::CVString const&, char const_) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
  "std::istream::read(char_, long)", referenced from:
      _baidu_framework::MergeNamePart(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, int) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::MergeIndexPart(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::MergeDataPart(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, _baidu_framework::tagVectorMapFile&, int) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::CheckPatchMd5(std::basic_fstream<char, std::char_traits<char> >&) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::HandleBasemapMerge(_baidu_vi::CVString const&, _baidu_vi::CVString const&, _baidu_vi::CVString const&, char const_) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
  "std::istream::seekg(long long, std::_Ios_Seekdir)", referenced from:
      _baidu_framework::MergeIndexPart(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::MergeDataPart(std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, std::basic_fstream<char, std::char_traits<char> >&, _baidu_framework::tagVectorMapFile&, int) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
      _baidu_framework::CheckPatchMd5(std::basic_fstream<char, std::char_traits<char> >&) in BaiduMapAPI_Map(BVMDOfflineMapMerge.o)
**

**Comment by yiyangest** [comment]
少添加了framework吧， CoreTelephony.framework，参考一下百度地图官网文档里的[配置](http://lbsyun.baidu.com/index.php?title=iossdk/guide/buildproject)

**Comment by samproppp** [comment]
完成！
