### ISSUE TITLE
不管模拟器，真机运行后一直出现异常

### ISSUE THREAD

**Issue by liz1113012618** [yiyangest/react-native-baidumap#4]
"react-native": "^0.20.0",
    "react-native-baidumap": "0.0.14",

我按照上面Android的配置好后，不管用模拟器或者真机调试都意外退出，并且显示好多文件都找不到
![430d9f93-b29c-4d34-a04b-7d98cfb2be7c](https://cloud.githubusercontent.com/assets/18205523/16073487/a51be56c-3318-11e6-8c12-6d7364031605.png)

能帮忙解决下么

**Comment by liz1113012618** [comment]
Android 配置好后，运行不报错，但是一启动就自动退出，请问这是什么原因啊？
![7dc5fcac-23a1-4feb-a4b2-7cf862ba8178](https://cloud.githubusercontent.com/assets/18205523/16075390/5a24aab8-3321-11e6-8c90-4c4bf27369d5.png)

**Comment by yiyangest** [comment]
错误日志打印的是什么
