### ISSUE TITLE
关于Android定位不能放大问题

### ISSUE THREAD

**Issue by liz1113012618** [yiyangest/react-native-baidumap#6]
![eb5uclrwdnbjhk1zs sps2j](https://cloud.githubusercontent.com/assets/18205523/16144014/f40dd23a-34a2-11e6-824f-322e816ba11b.jpg)
![hvi ezqi k22l _ l bleo4](https://cloud.githubusercontent.com/assets/18205523/16144015/f5ba5eb4-34a2-11e6-9102-a5c55e4155d6.jpg)
![k bdq3 lai11o6fhi5xmw](https://cloud.githubusercontent.com/assets/18205523/16144017/f6e91e10-34a2-11e6-9bbb-449d46feea10.jpg)

请问这个问题怎么解决，一调用这个方法就会报上面的错this.refs["mapView"].zoomToLocs([[this.state.lastPositionlatitude, this.state.lastPositionlongitude]]);

**Comment by yiyangest** [comment]
react-native版本多少？

**Comment by yiyangest** [comment]
新版本的react-native升级后，findNodeHandle这个方法从原来的React包里移到了React-native包里，可以把`React.findNodeHandle` 改成 `ReactNative.findNodeHandle`  (前提是`import ReactNative from 'react-native'`)

**Comment by liz1113012618** [comment]
"react-native": "^0.20.0",
    "react-native-baidumap": "0.0.14",
‘把React.findNodeHandle 改成 ReactNative.findNodeHandle (前提是import ReactNative from 'react-native')’按上面改完后，我发现了新问题，你的示例代码里面有一段定位代码，我发现Android真机定位后经纬度一直是0，0，请问这是什么原因呢？

**Comment by yiyangest** [comment]
经纬度一直是0的话，有相关的上下文日志信息吗
